version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis
    volumes_from:
      - datastore
  web:
    build: .
    command: ./bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes_from:
      - datastore
  cable:
    build: .
    command: ./bin/cable
    ports:
      - "28080:28080"
    volumes_from:
      - datastore
  datastore:
    image: busybox
    command: echo data container for app
    volumes:
      - /datastore
